### ISSUE TITLE
Print statements

### ISSUE THREAD

**Issue by qo4on** [krassowski/jupyter-manim#12]
Is it possible to see `print` statements which were defined in `def construct(self)` next to playback window in Jupyter?

**Comment by krassowski** [comment]
Copy-paste from README:
> The `%%manim` magic (by default) hides the progress bars as well as other logging messages generated by manim. You can disable this behaviour using `--verbose` flag.

Let me know if it helps.

**Comment by qo4on** [comment]
Sorry, sir. I feel so stupid.
