### ISSUE TITLE
Doesn't work with Text object

### ISSUE THREAD

**Issue by qo4on** [krassowski/jupyter-manim#13]
```
%%manim Shapes --base64 --low_quality --verbose

class Demo(Scene):
  def construct(self):
    text = Text('Hello, world!')
    self.play(Write(text))
```

> Media will be written to ./media/. You can change this behavior with the --media_dir flag.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> /tmp/tmpgj01amj5.py:15: UserWarning: Import from notebook: name already in the globals(), skipping
>   warn('Import from notebook: ' + name + ' already in the globals(), skipping')
> 
>    Shapes is not in the script
> 
> Traceback (most recent call last):
>   File "/content/manim/manimlib/extract_scene.py", line 155, in main
>     scene = SceneClass(**scene_kwargs)
>   File "/content/manim/manimlib/scene/scene.py", line 53, in __init__
>     self.construct()
>   File "/tmp/tmpgj01amj5.py", line 23, in construct
>     text = Text('Hello, world!')
> TypeError: __init__() takes 1 positional argument but 2 were given

It works with command line:
`!python3 -m manim example_scenes.py Demo -pl`

**Comment by krassowski** [comment]
> Shapes is not in the script

You are not rendering the `Demo` scene class, instead, you attempt to render a `Shapes` scene class.

`%%manim Shapes --base64 --low_quality --verbose`

should be

`%%manim Demo --base64 --low_quality --verbose`

**Comment by qo4on** [comment]
I have a lot of examples (more than 100) where it works in this way.
![image](https://user-images.githubusercontent.com/35609308/74610495-8d006d80-5115-11ea-9951-da21f65e77ee.png)
Actually I didn't notice that I have to change `Shapes`. I changed the `class...` and didn't touch the first line every time. And there were no errors.
Can you explain why this is happening?

**Comment by qo4on** [comment]
I found the issue. When I uninstall `jupyter-manim` and install it again the `Text` class becomes unreachable for the whole notebook.

**Comment by krassowski** [comment]
I am happy that you found the culprit. It seems that it is not an issue with this package. Please re-open if any action is needed.
