### ISSUE TITLE
Embedded player shows duplicates.

### ISSUE THREAD

**Issue by qo4on** [krassowski/jupyter-manim#14]
If you stop playback and try move frame by frame with arrows on the keyboard you will see duplicate frames. The same file in other player has no duplicates. I'm not sure is this a bug or not, but it's inconvenient.

**Comment by krassowski** [comment]
Thank you for reporting this. I guess that this is a browser-dependent behaviour and as such cannot be fixed in the package itself. Please feel free to add more comments after checking out how it works in different browsers/re-open if you can point to how this can be addressed in this package.
