### ISSUE TITLE
%%manim not found

### ISSUE THREAD

**Issue by bwanaaa** [krassowski/jupyter-manim#2]
I properly installed manim and can get the example_scenes.py to render.
I properly installed jupyter manim and conda list shows it:
`
jupyter-manim             0.11                     pypi_0    pypi`

I started jupyter notebook from a terminal initiated from within the manim folder
I entered this in the first cell:
```
%%manim Shapes
from manimlib.scene.scene import Scene
from manimlib.mobject.geometry import Circle
from manimlib.animation.creation import ShowCreation

class Shapes(Scene):

    def construct(self):
        circle = Circle()
        self.play(ShowCreation(circle))

```
and got
UsageError: Cell magic `%%manim` not found.

**Comment by krassowski** [comment]
Did you `import jupyter_manim` in a cell before?

**Comment by bwanaaa** [comment]
*shakes head*
I feel sooo stupid...

**Comment by krassowski** [comment]
Happy to help! Thanks for letting me know, I missed this in the description. I changed the usage section in README to make it more obvious.

**Comment by qo4on** [comment]
I can't hit play:
![image](https://user-images.githubusercontent.com/35609308/74083437-ce45ad00-4a85-11ea-9e66-a17b314181f6.png)

**Comment by krassowski** [comment]
For Colab you need `--base64`, please [read the README file](https://github.com/krassowski/jupyter-manim#video-player-control-options).

**Comment by krassowski** [comment]
Specifically, you would need to replace `%%manim Shapes` with `%%manim Shapes --base64`.
