### ISSUE TITLE
can't build pycario on google colab

### ISSUE THREAD

**Issue by FrankHui** [krassowski/jupyter-manim#28]
Hi, I run pip3 install jupyter_manim, everything is installed successfully but below

> Building wheels for collected packages: pycairo
>   Building wheel for pycairo (PEP 517) ... error
>   ERROR: Failed building wheel for pycairo
>   Running setup.py clean for pycairo
> Failed to build pycairo
> ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly

I've checked [travis.yml](https://github.com/krassowski/jupyter-manim/blob/master/.travis.yml), which I guess what "pip3 install jupyter_manim" follow.  Google colab provide linux vm so I think it shouldn't install pycario?

Anyway, Should I run command line by line like [this](https://gist.github.com/Macorreag/abfc02b99a751431d8793e9c5506ef49?)

**Comment by krassowski** [comment]
This looks like Google Colab user support query - sorry it looks I cannot help with this one!

**Comment by pwichmann** [comment]
Just add this to colab before you pip install pycairo:

```bash
# Required for pycairo
!sudo apt install libcairo2-dev pkg-config python3-dev
```

I know I am a year late but maybe someone else googles this problem.

**Comment by sugatoray** [comment]
There is another resource on the same. It basically references the previous comment and states that the said solution works. 

:fire: I have personally tried this on colab, and can confirm that it works.

- https://nickwan.github.io/pycairo-and-colab/

```sh
# Required for pycairo
! sudo apt install libcairo2-dev pkg-config python3-dev
! pip install pycairo
```

cc: @pwichmann Thank you. :rocket:
