### ISSUE TITLE
Manim cell output doesn't play using `<source>` tag in vscode v1.59.1

### ISSUE THREAD

**Issue by mavyfaby** [krassowski/jupyter-manim#29]
## Description

I don't know if this only happens to me.
Given this example, when I run the code. The video output doesn't play.
![Screenshot from 2021-08-31 19-13-22](https://user-images.githubusercontent.com/51808724/131494655-5339f89e-1e0c-48ce-b624-fc795c4dc156.png)

## Reproduce

1. Install or open vscode v1.59.1 (I don't know if this only happens in this version)
2. Write some code for manim
3. Then execute cells

The video file output is present and can be played but in jupyter manim output, it doesn't play. I test by removing `source` from `video` tag and adding `src` attribute in `video` tag and it works. I'll make a PR for this issue if this issue is valid.

![Screenshot from 2021-08-31 19-15-02](https://user-images.githubusercontent.com/51808724/131495835-d9a4694c-5264-4858-8d2a-692f6eaf721e.png)

## Expected behavior

The manim output should play.

## Context

- Operating System and version: **Linux Ubuntu 20.04**
- Browser and version:  **Chrome 92.0.4515.159 (Official Build) (64-bit)**
- JupyterLab version:  ***Not Installed*, using jupyter extension from vscode**

```txt
jupyter core     : 4.7.0
jupyter-notebook : 6.1.6
qtconsole        : 5.0.1
ipython          : 7.19.0
ipykernel        : 5.4.2
jupyter client   : 6.1.7
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.2
nbformat         : 5.0.8
traitlets        : 5.0.5
```

**Comment by krassowski** [comment]
This looks like a problem in VSCode, not in this package as I believe that the use of `<source>` tag is correct. I would recommend you open an issue in vscode-python repository.

**Comment by mscharling** [comment]
I've had the same issue and got net::ERR_FILE_NOT_FOUND looking into the DevTools Console when opening my build in Chrome. I found out that my media folder wasn't properly placed into the .../_build/html folder. Is there some way to make sure that the media-folder is placed into .../_build/html everytime you execute the notebook?
