### ISSUE TITLE
Feature request for exporting the current namespace

### ISSUE THREAD

**Issue by leemengtw** [krassowski/jupyter-manim#5]
Hi, thanks for the great job for bring manim to jupyter!

I'm just wondering if we can have the feature as written in the readme?

```text
In future, an option to export the current namespace (or specific variables) will be added. It could be implemented by pickling the Python locals and globals and then pre-pending the cell with an un-pickling script
```

It will be very helpful!

**Comment by spencerpogo** [comment]
I'm not really sure what it means by "export", what were you thinking @leemengtaiwan

**Comment by leemengtw** [comment]
@Scoder12 I think it's very clear in the message that is written by the author in the README before.

At the time I raised the issue, one have to write all the manim code **inside a single cell** rather than having the freedom of developing code in multi-cell in jupyter.

**Comment by leemengtw** [comment]
@krassowski kudo for your work, this is awesome!!!
